worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    upstream canvas_backend {
        server server1:8001;
        server server2:8002;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 8080;
        server_name localhost;

        # CORS Headers
        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept, Origin, User-Agent' always;

        location /ws/ {
            proxy_pass http://canvas_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_buffering off;
        }

        location /auth/ {
            proxy_pass http://auth:8003/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://host.docker.internal:3000;
            proxy_set_header Host $host;
        }
        location /rooms/ {
            proxy_pass http://auth:8003/rooms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /rooms {
            proxy_pass http://auth:8003/rooms;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}